apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.DB.Service.Name }}
spec:
  selector:
    app.kubernetes.io/name: db
  ports:
  - name: {{ .Values.DB.Service.Ports.Name }}
    protocol: TCP
    port: {{ .Values.DB.Service.Ports.Port }}
    targetPort: db-port