apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Web.Service.Name }}
spec:
  selector:
    app.kubernetes.io/name: web
  ports:
  - name: {{ .Values.Web.Service.Ports.Name }}
    protocol: TCP
    port: {{ .Values.Web.Service.Ports.Port }}
    targetPort: http-web