apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.Web.Pod.Name }}
  labels:
    app.kubernetes.io/name: web

spec:
  containers:
  - name: {{ .Values.Web.Container.Name }}
    image: "{{ .Values.Web.image.repository }}/{{ .Values.Web.image.name }}:{{ .Values.Web.image.tag | default .Chart.AppVersion }}"
    imagePullPolicy: {{ .Values.Web.image.pullPolicy }}
    ports:
    - containerPort: 80
      name: http-web