apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app.kubernetes.io/name: db
  ports:
  - name: db-service-port
    protocol: TCP
    port: 9906
    targetPort: db-svc-port