apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app.kubernetes.io/name: web
  ports:
  - name: php-service-port
    protocol: TCP
    port: 8000
    targetPort: http-web-svc